### ISSUE TITLE
Strings that contain typable names get wrongly typed

### ISSUE THREAD

**Issue by giltho** [ocaml/merlin#1116]
Hi !
In a code like this one for example:
```
let some_int = 5
let x = "some_int"
```

When hovering inside the string, the given type is `int` (first element returns by `type_enclosing`). Merlin should probably only return `string`. I do not know if this is desired behaviour or not.

See [this issue](https://github.com/ocaml/ocaml-lsp/issues/66) of ocaml-lsp for more details :)

Thank you !

**Comment by rgrinberg** [comment]
@voodoos this is fixed I believe?

**Comment by voodoos** [comment]
It is not fixed yet. At first I thought the recent refactoring of `Type_enclosing` with better context usage would make this trivial to fix but in fact it needs more ground work to be done before.

(See this comment: )
