### ISSUE TITLE
UTF-8 documentation should work

### ISSUE THREAD

**Issue by Chris00** [ocaml/merlin#710]
When calling `merlin-document` (in Emacs) on a function whose documentation contains UTF-8 symbols, the message or buffer displayed contains "garbage" instead of the original symbols.

**Comment by let-def** [comment]
Should be fixed in master. Can you test?

**Comment by Chris00** [comment]
It is not complete.  It seems to output the right bytes as copying the message gives
```
(* Computes cos(x) for x ∈ ]-2⁶³, 2⁶³[. *)
```
but in Emacs I see (even though the buffer is in UTF-8):
![emacs-type](https://user-images.githubusercontent.com/1255665/29898442-1621813a-8de6-11e7-87d2-564ff0c1572f.png)

**Comment by Chris00** [comment]
Don't know whether it is related but sometimes Merlin report types such as
```
b:(float -> float) ->¯loat ->
speed:float ->¯loat ->
(float, Bigarray.float64_elt, Bigarray.fortran_layout) Bigarray.Array1.t
```
(notice the `¯loat` instead of `float`).

**Comment by let-def** [comment]
This is strange and I cannot reproduce. On my system I get proper utf-8 support. Maybe this has to do with some default.

What is your locale (and operating system)?
Also would you mind trying to investigate from your side as you are probably more knowledgeable on Emacs lisp than I am :) (I will help of course).

**Comment by Chris00** [comment]
The first problem is fixed with the above commit.

For the second one, the funny thing is that the first time I request the type it prints `b:(float -> float) -> float -> speed:float -> float -> Odepack.vec` while — without moving the cursor — I request it a second time, it prints `b:(float -> float) ->¯loat ->
speed:float ->¯loat ->
(float, Bigarray.float64_elt, Bigarray.fortran_layout) Bigarray.Array1.t`.  Both are correct but the second one has the `¯loat` problem (this is not a unibyte/multibyte problem, it rather seems to come from Merlin).

**Comment by Chris00** [comment]
Running with `(setq merlin-debug t)` yields (truncated):
```
# calling binary: "/home/trch/.opam/4.04.0/bin/ocamlmerlin" with arguments: ("server" "type-enclosing" "-protocol" "sexp" "-log-file" "-" "-verbosity" "2" "-filename" "/home/trch/research/Feltrin/superlinear-sign-changing/ocaml/ode.ml" "-position" "12:5" "-index" "0").
# stdout
((assoc) (class . "return") (value ((assoc) (start (assoc) (line . 12) (col . 4)) (end (assoc) (line . 12) (col . 7)) (type . "b:(float -> float) ->\x0Afloat ->\x0Aspeed:float ->\x0Afloat ->\x0A(float, Bigarray.float64_elt, Bigarray.fortran_layout) Bigarray.Array1.t") (tail . "no"))) (notifications) (timing (assoc) (total . 2.01) (query . 0.824) (reader . 0.625) (ppx . 0.018) (typer . 0.543) (error . 0.)))
...
# 0.35 New_commands.run - result
[
  {
    "start": { "line": 12, "col": 4 },
    "end": { "line": 12, "col": 7 },
    "type":
      "b:(float -> float) ->\nfloat ->\nspeed:float ->\nfloat ->\n(float, Bigarray.float64_elt, Bigarray.fortran_layout) Bigarray.Array1.t",
    "tail": "no"
  }
]
```

**Comment by Chris00** [comment]
I guess the problem is that merlin prints the type with `\x0A` in the result.  In Emacs, evaluating `(insert "\x0Afloat")` indeed gives `¯loat`.

**Comment by let-def** [comment]
Thanks that is very helpful. I missed a case in sexp serialization... Strange I didn't see it earlier.

**Comment by Chris00** [comment]
@let-def Great the culprit is found! — let me know when it is fixed (I use the git version of merlin, I can test it).

**Comment by Chris00** [comment]
@let-def Any news on the fix to the sexp serialization?

**Comment by let-def** [comment]
I just pushed the fix on git repository. Can you try if it solves your problem?
My hope is that it should fix https://github.com/ocaml/merlin/pull/738 too.

**Comment by Chris00** [comment]
Your commit fixes the `\n` issue.  Without https://github.com/ocaml/merlin/pull/738, the documentation problem is not fixed.

P.S. When displaying in the minibuffer, why not try to remove rewrap the type to minimize the number of newlines?  For example, the above type is displayed as
```ocaml
b:(float -> float) ->
float ->
speed:float ->
float ->
(float, Bigarray.float64_elt, Bigarray.fortran_layout) Bigarray.Array1.t
```
but would be as readable as
```ocaml
b:(float -> float) -> float -> speed:float -> float ->
(float, Bigarray.float64_elt, Bigarray.fortran_layout) Bigarray.Array1.t
```
(when showing `*merlin-types*`, it is fine to have one type per line).  One-type-per-line is indeed not systematically used: the first type to be displayed for the function is
```ocaml
b:(float -> float) -> float -> speed:float -> float -> Odepack.vec
```
(all on a single line).

**Comment by Chris00** [comment]
@let-def ping?

**Comment by Chris00** [comment]
I did some experiments: if
```elisp
(let* ((s "((assoc) (class . \"return\") (value . \" [acos a] raise [Domain_error] if [a.low>1. or a.high<-1.],\x0A     else returns [{low=if a.high<1. then acos a.high else 0; high=if\x0A     a.low>-1. then acos a.low else pi}].  All values are in \[0,π\].\") (notifications) (timing (assoc) (total . 32.898) (query . 10.678) (reader . 7.104) (ppx . 0.034) (typer . 15.082) (error . 0.)))")
      (r (read-from-string s)))
  (message "̱▸▸▸ %s" r))
```
works, the following does not:
```elisp
(let* ((s "((assoc) (class . \"return\") (value . \" [acos a] raise [Domain_error] if [a.low>1. or a.high<-1.],\x0A     else returns [{low=if a.high<1. then acos a.high else 0; high=if\x0A     a.low>-1. then acos a.low else pi}].  All values are in \[0,\xCF\x80\].\") (notifications) (timing (assoc) (total . 32.898) (query . 10.678) (reader . 7.104) (ppx . 0.034) (typer . 15.082) (error . 0.)))")
      (r (read-from-string s)))
  (message "̱▸▸▸ %s" r))
```
The only difference is that π is replaced by its UTF8 representation `\xCF\x80`.

IMHO, there are two solutions:
```elisp
(let* ((s "((assoc) (class . \"return\") (value . \" [acos a] raise [Domain_error] if [a.low>1. or a.high<-1.],\x0A     else returns [{low=if a.high<1. then acos a.high else 0; high=if\x0A     a.low>-1. then acos a.low else pi}].  All values are in \[0,\xCF\x80\].\") (notifications) (timing (assoc) (total . 32.898) (query . 10.678) (reader . 7.104) (ppx . 0.034) (typer . 15.082) (error . 0.)))")
      (r (read-from-string (string-as-multibyte s))))
  (message "̱▸▸▸ %s" r))
```
works — telling Emacs that the string is to be interpreted as multibyte.
But I also wonder — have not checked the sexp rules — whether [escaping entities (except `"`)](https://github.com/ocaml/merlin/blob/master/src/utils/sexp.ml#L39-L46) is really necessary.  If I remove that escaping, both `\n` (for the ¯loat problem above) and π are understood properly.

**Comment by let-def** [comment]
Thanks for all the time you spent on this issue. I added a single call to `string-as-multibyte` after reading input from merlin.
Is it working as you expect?

**Comment by Chris00** [comment]
It works fine if I comment out the [escaping](https://github.com/ocaml/merlin/blob/master/src/utils/sexp.ml#L39-L46) — in which case, `string-as-multibyte` does not seem to actually be required.

**Comment by let-def** [comment]
But when the escaping is there, `string-as-multibyte` is not enough to make things work?
(I am trying to understand what emacs is doing there :P..., I had problem with escaping before, that's why I would like to keep it, but maybe it was due to something else)

**Comment by Chris00** [comment]
Experiments show that you do not need to apply `string-as-multibyte` to the whole result but to `(alist-get 'value result)` only (after `read-from-string` thus).

**Comment by let-def** [comment]
But I suspect that not escaping should give the same result as escaping and immediately using string-as-multibyte.

**Comment by Chris00** [comment]
Keeping the escaping in place, the following works:
```elisp
    (condition-case err
        (setq result (car (read-from-string result)))
      (error
        (error "merlin: error %s trying to parse answer: %s"
               err result)))
    (let ((v (assq 'value result)))
      (setcdr v (string-as-multibyte (cdr v))))
```

**Comment by Chris00** [comment]
Do you want me to submit a PR?

**Comment by let-def** [comment]
What happens with the current code (doing `(read-from-string (string-as-multibyte result))`)?

**Comment by Chris00** [comment]
To understand what is going on, here is—displayed with `(message "%s" result)`—the original value of `result` (folded to ease readability):
```elisp
((assoc) (class . "return") (value . " [compare_f a x] returns\x0A      
      - [1] if [a.high < x],\x0A
      - [0] if [a.low <= x <= a.high], i.e., if [x] \xE2\x88\x88 [a], and\x0A
      - [-1] if [x < a.low].  ") (notifications) (timing (assoc) (total . 35.128) (query . 4.838) (reader . 10.002) (ppx . 0.111) (typer . 20.177) (error . 0.)))
```
Oh this, `string-as-multibyte` has not effect:
```elisp
((assoc) (class . "return") (value . " [compare_f a x] returns\x0A
      - [1] if [a.high < x],\x0A
      - [0] if [a.low <= x <= a.high], i.e., if [x] \xE2\x88\x88 [a], and\x0A
      - [-1] if [x < a.low].  ") (notifications) (timing (assoc) (total . 35.128) (query . 4.838) (reader . 10.002) (ppx . 0.111) (typer . 20.177) (error . 0.)))
```
probably because the escape sequences are still separate chars.  After applying `read-from-string`, the value of `(alist-get 'value result)` is
```
[compare_f a x] returns
      - [1] if [a.high < x],
      - [0] if [a.low <= x <= a.high], i.e., if [x] \342\210\210 [a], and
      - [-1] if [x < a.low].  
```
where `\342\210\210` is to be read as **three** characters (thus decoded from their escapings) interpreted as unibyte (this is expected given [Emacs rules](https://www.gnu.org/software/emacs/manual/html_node/elisp/Non_002dASCII-in-Strings.html)).  Converting the string as multibyte then does the trick:
```
[compare_f a x] returns
      - [1] if [a.high < x],
      - [0] if [a.low <= x <= a.high], i.e., if [x] ∈ [a], and
      - [-1] if [x < a.low].  
```

**Comment by let-def** [comment]
I think I understand, many thanks for taking the time to explain.
I trust you to do the right thing, if you can submit a PR I will merge it :).
